# Listener TCP principal
listener 1883
allow_anonymous true

# Listener WebSocket
listener 9001
protocol websockets
allow_anonymous true

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_type all
